### ISSUE TITLE
[form dinamici] Gestione PEO form

### ISSUE THREAD

**Issue by cappe87** [UniversitaDellaCalabria/PEO#10]
Dopo aver accettato il consenso al trattamento dei dati si riceve l'errore in allegato:
![errore_peo](https://user-images.githubusercontent.com/6532945/59863960-1e9cbd00-9386-11e9-9737-5acb0a028c0a.png)

**Comment by peppelinux** [comment]
Puoi fare pull perché questa eccezione è derivata da un refuso tra un commit e l'altro. Con l'app form-builder e gli ultimi commit questo codice non esiste ne tantomeno l'eccezione.
